CREATE TABLE IF NOT EXISTS hits
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    app       VARCHAR(80)                             NOT NULL,
    uri       VARCHAR(255)                            NOT NULL,
    ip        VARCHAR(100)                            NOT NULL,
    timestamp TIMESTAMP WITHOUT TIME ZONE
);